version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ENV: ${ENV}
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=${MONGO_URI}
      - REDIS_URL=${REDIS_URL}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - KAKAO_CLIENT_ID=${KAKAO_CLIENT_ID}
      - KAKAO_CLIENT_SECRET=${KAKAO_CLIENT_SECRET}
      - KAKAO_REDIRECT_URI=${KAKAO_REDIRECT_URI}
      - SECRET_KEY=${SECRET_KEY}
    depends_on:
      - redis

  redis:
    image: redis:latest
    ports:
      - "11721:11721"
